project:
  type: website
  output-dir: docs

website:
  title: "2025 창의융합과제연구"
  navbar:
    left:
      - href: project1-2.ipynb
        text: project1-2

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



